# Generated by Django 4.2.8 on 2024-03-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_admin_tbl_brand_tbl_category_tbl_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_services',
            name='services_details',
            field=models.CharField(max_length=500),
        ),
    ]
