# Generated by Django 4.2.8 on 2024-03-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_alter_tbl_services_services_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_services',
            name='services_details',
            field=models.TextField(),
        ),
    ]
