# Generated by Django 4.2.8 on 2024-03-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_remove_tbl_office_place'),
        ('User', '0002_alter_tbl_complaint_office'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_office',
        ),
    ]
