# Generated by Django 4.2.8 on 2024-03-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_delete_tbl_office'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_brand',
        ),
        migrations.DeleteModel(
            name='tbl_product',
        ),
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
