# Generated by Django 4.2.8 on 2024-03-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_delete_tbl_brand_delete_tbl_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_services',
        ),
    ]
