# Generated by Django 4.2.8 on 2024-03-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_delete_tbl_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(max_length=500)),
                ('services_details', models.CharField(max_length=500)),
                ('services_criteria', models.CharField(max_length=500)),
                ('services_document', models.FileField(upload_to='Assests/ServiceDocs/')),
            ],
        ),
    ]
