# Generated by Django 4.2.8 on 2024-03-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_knowlederepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowrepo_title', models.CharField(max_length=500)),
                ('knowrepo_details', models.CharField(max_length=500)),
                ('knowrepo_document', models.FileField(upload_to='Assests/KnowledegeDocs/')),
            ],
        ),
    ]
