# Generated by Django 4.2.8 on 2024-03-11 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_place'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_contact', models.CharField(max_length=50)),
                ('shop_email', models.CharField(max_length=50)),
                ('shop_address', models.CharField(max_length=50)),
                ('shop_logo', models.FileField(upload_to='userdocs/')),
                ('shop_proof', models.FileField(upload_to='userdocs/')),
                ('shop_password', models.CharField(max_length=50)),
                ('shop_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
