# Generated by Django 4.2.8 on 2024-03-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.FileField(upload_to='Assests/UserDocs/'),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_proof',
            field=models.FileField(upload_to='Assests/UserDocs/'),
        ),
        migrations.DeleteModel(
            name='tbl_shop',
        ),
    ]
