# Generated by Django 4.2.8 on 2024-03-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_remove_tbl_office_place'),
        ('Guest', '0003_alter_tbl_user_user_photo_alter_tbl_user_user_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=50)),
                ('office_contact', models.CharField(max_length=50)),
                ('office_email', models.CharField(max_length=50)),
                ('office_address', models.CharField(max_length=50)),
                ('office_logo', models.FileField(upload_to='Assests/OfficeDocs/')),
                ('office_proof', models.FileField(upload_to='Assests/OfficeDocs/')),
                ('office_password', models.CharField(max_length=50)),
                ('office_status', models.IntegerField(default=0)),
                ('office_doj', models.DateField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
