# Generated by Django 4.2.8 on 2024-03-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_tbl_complaint_office'),
        ('Guest', '0004_tbl_office'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_office',
        ),
    ]
