# Generated by Django 4.2.8 on 2024-03-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_chat',
            name='office_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_from', to='Guest.tbl_office'),
        ),
        migrations.AlterField(
            model_name='tbl_chat',
            name='user_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user'),
        ),
        migrations.AlterField(
            model_name='tbl_chat',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user'),
        ),
    ]
