# Generated by Django 4.2.8 on 2024-03-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_tbl_admin_tbl_brand_tbl_category_tbl_product_and_more'),
        ('Guest', '0002_tbl_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(max_length=100)),
                ('feedback_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_location', models.CharField(max_length=50)),
                ('land_description', models.CharField(max_length=50)),
                ('land_photo', models.FileField(upload_to='userdocs/landphotos/')),
                ('land_doa', models.DateField(auto_now_add=True)),
                ('land_measurement', models.IntegerField(null=True)),
                ('land_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_doc', models.CharField(max_length=100)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('land', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_land')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=100)),
                ('complaint_content', models.CharField(max_length=100)),
                ('complaint_reply', models.CharField(max_length=100)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_office')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
