# Generated by Django 4.2.8 on 2024-03-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_tbl_complaint_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
        migrations.RemoveField(
            model_name='tbl_land',
            name='place',
        ),
        migrations.RemoveField(
            model_name='tbl_land',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='land',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_land',
        ),
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
