# Generated by Django 4.2.8 on 2024-03-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_chat_office_from_alter_tbl_chat_office_to'),
        ('Admin', '0013_tbl_services'),
        ('User', '0007_tbl_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sellingland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_location', models.CharField(max_length=50)),
                ('land_contact', models.IntegerField(null=True)),
                ('land_landmark', models.EmailField(max_length=50)),
                ('land_address', models.CharField(max_length=50)),
                ('land_landimage', models.FileField(upload_to='Assests/LandImage/')),
                ('land_proof', models.FileField(upload_to='Assests/LandProof/')),
                ('land_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
